common:
	 @sh components/common.sh
frontend: common # This will make common execute first
	 @sh components/frontend.sh
mongo: common
	 @sh components/Mongo.sh
catalogue: common
	 @sh components/catalogue.sh